[versions]
androidGradlePluginVersion = "8.8.0"
composeWebviewMultiplatformVersion = "1.9.40"
jlleitschuhGradleKtlintVersion = "12.1.2"
composeMultiplatform = "1.7.0"
kotlinVersion = "2.0.20"
composeLifecycleViewModelVersion = "2.8.4"
materialIconsCoreVersion = "1.7.3"
ktor = "3.0.3"
datastore = "1.1.1"
koin = "4.0.0"
koinComposeMultiplatform = "4.0.0"
lifecycleViewModel = "2.8.4"
skie ="0.10.9"
navigation-compose = "2.8.0-alpha10"
kotlinx-datetime = "0.6.1"
calf-file-picker = "0.5.0"
coilCompose3Version = "3.0.4"
gemini-common = "0.9.0-1.1.0"
buildkonfig = "0.15.2"


 [libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePluginVersion" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatformVersion" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinVersion" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
calf-file-picker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf-file-picker" }

coil3-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coilCompose3Version" }
coil3-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilCompose3Version" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-view-model = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeLifecycleViewModelVersion" }

material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "materialIconsCoreVersion" }



ktor-client-core = { group= "io.ktor", name="ktor-client-core", version.ref ="ktor" }
ktor-client-okhttp = { group= "io.ktor", name="ktor-client-okhttp", version.ref ="ktor" }
ktor-client-darwin = { group= "io.ktor", name="ktor-client-ios", version.ref ="ktor" }
ktor-client-contentnegotiation = { group= "io.ktor", name="ktor-client-content-negotiation", version.ref ="ktor" }
ktor-client-serialization-json = { group= "io.ktor", name="ktor-serialization-kotlinx-json", version.ref ="ktor" }

datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewModel"}
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinComposeMultiplatform" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeMultiplatform" }

androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name="navigation-compose", version.ref = "navigation-compose" }
generative-ai = { module = "dev.shreyaspatil.generativeai:generativeai-google", version.ref = "gemini-common" }

 [plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePluginVersion" }
android-library = { id = "com.android.library", version.ref = "androidGradlePluginVersion" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "jlleitschuhGradleKtlintVersion" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinVersion" }

kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinVersion" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }

